### ISSUE TITLE
. 

### ISSUE THREAD

**Issue by Rajagopalhertzian** [nicolay-r/Awesome-Image-Captioning-MLLMs#1]

**Comment by nicolay-r** [comment]
Hey @Rajagopalhertzian, thanks for your interest in repo and content! 
I've just recently started to explore this field and therefore soon drop some updates.
 Please stand by 🙏

**Comment by nicolay-r** [comment]
@Rajagopalhertzian, just a quick update that already started to publish personal updates and advances. Feel free to check out, give comments and ask questions!

**Comment by Rajagopalhertzian** [comment]
Thanks for your response
